name: CI/CD Workflow


on:
   push:
    branches:
      -main




jobs:
build:
runs-on ubuntu-latest
steps:
  -name: Checkout repository
   users:actions/checkout@v3
  -mans: Run a test command
   run: echo "GitHub Actions is working"

